Added support for arbitrarily sized cells; performed some clean-up.

diff --git a/warden/bin/create-cell b/warden/bin/create-cell
--- a/warden/bin/create-cell
+++ b/warden/bin/create-cell
@@ -2,7 +2,7 @@
 # Creates a new cell.
 
 name="$1"
-ipx="$2"
+ipBase="$2"
 spec="$3"
 shift 3
 key="$@"
@@ -18,24 +18,33 @@ mininet=${spec##*+}
 
 ssh 10.192.19.220 "grep -qF \"$key\" /home/sdn/.ssh/authorized_keys || echo $key >> /home/sdn/.ssh/authorized_keys"
 
+# Validate that the cell-spec is viable
+nodeCount=$(echo $spec | bc)
+[ $nodeCount -gt 13 ] && echo "Unable to create $nodeCount node cell" >&2 && exit 2
+
+# Split the IP base address into a prefix and a suffix that can be incremented.
+ipPrefix=${ipBase%.*}
+ipSuffix=${ipBase##*.}
+
 if [ $mininet -ge 1 ]; then
-    ./clone-node base-mininet ${ipx/x/0} $name-n "$key" &
+    ./clone-node base-mininet $ipBase $name-n "$key" &
     sleep 1
 fi
 
+let ip=ipSuffix+1
 let n=1
 while [ $n -le $cores ]; do
-    ./clone-node base-onos ${ipx/x/$n} $name-c$n "$key" &
+    ./clone-node base-onos ${ipPrefix}.${ip} $name-c$n "$key" &
     let n=n+1
+    let ip=ip+1
     sleep 1
 done
 
-let a=n
 let n=1
 while [ $n -le $nodes ]; do
-    ./clone-node base-onos ${ipx/x/$a} $name-$n "$key" &
+    ./clone-node base-onos ${ipPrefix}.${ip} $name-$n "$key" &
     let n=n+1
-    let a=a+1
+    let ip=ip+1
     sleep 1
 done
 
